//
//  ListOrdersWorkerTests.swift
//  CleanStore
//
//  Created by msm72 on 10.08.16.
//  Copyright (c) 2016 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class ListOrdersWorkerTests: XCTestCase {
    // MARK: - Subject under test
    var sut: ListOrdersWorker!
  
  
    // MARK: - Test lifecycle
    override func setUp() {
        super.setUp()
    
        setupListOrdersWorker()
    }
  
    override func tearDown() {
        super.tearDown()
    }
  
  
    // MARK: - Test setup
    func setupListOrdersWorker() {
        sut = ListOrdersWorker()
    }
  
  
    // MARK: - Test doubles
  
  
    // MARK: - Tests
    func testSomething() {
        // Given
    
    
        // When
    
    
        // Then
    }
}

