//
//  ListOrdersViewControllerTests.swift
//  CleanStore
//
//  Created by msm72 on 10.08.16.
//  Copyright (c) 2016 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class ListOrdersViewControllerTests: XCTestCase {
    // MARK: - Subject under test
    var sut: ListOrdersViewController!
    var window: UIWindow!
  
  
    // MARK: - Test lifecycle
    override func setUp() {
        super.setUp()
        
        window = UIWindow()
        setupListOrdersViewController()
    }
  
    override func tearDown() {
        window = nil
    
        super.tearDown()
    }
  
  
    // MARK: - Test setup
    func setupListOrdersViewController() {
        let bundle = NSBundle.mainBundle()
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        
        sut = storyboard.instantiateViewControllerWithIdentifier("ListOrdersViewController") as! ListOrdersViewController
    }
  
    func loadView() {
        window.addSubview(sut.view)
        NSRunLoop.currentRunLoop().runUntilDate(NSDate())
    }
  
  
    // MARK: - Test doubles
  
    
    // MARK: - Tests
    func testSomething() {
        // Given
    
    
        // When
    
    
        // Then
    }
}

