# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'AlamofireGloss' do

pod 'Gloss', '~> 0.7'
pod 'Alamofire-Gloss', '~> 1.0'
pod 'Alamofire', '~> 3.4'

end

