//
//  CreateOrderInteractor.swift
//  CleanStoreTest
//
//  Created by msm72 on 05.08.16.
//  Copyright (c) 2016 Monastyrskiy Sergey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateOrderInteractorInput
{
  func doSomething(request: CreateOrderRequest)
}

protocol CreateOrderInteractorOutput
{
  func presentSomething(response: CreateOrderResponse)
}

class CreateOrderInteractor: CreateOrderInteractorInput
{
  var output: CreateOrderInteractorOutput!
  var worker: CreateOrderWorker!
  
    
  // MARK: Business logic
  func doSomething(request: CreateOrderRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = CreateOrderWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = CreateOrderResponse()
    output.presentSomething(response)
  }
}
