//
//  DeleteOrderViewController.swift
//  CleanStoreTest
//
//  Created by msm72 on 05.08.16.
//  Copyright (c) 2016 Monastyrskiy Sergey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DeleteOrderViewControllerInput
{
  func displaySomething(viewModel: DeleteOrderViewModel)
}

protocol DeleteOrderViewControllerOutput
{
  func doSomething(request: DeleteOrderRequest)
}

class DeleteOrderViewController: UIViewController, DeleteOrderViewControllerInput
{
  var output: DeleteOrderViewControllerOutput!
  var router: DeleteOrderRouter!
  
  // MARK: Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    DeleteOrderConfigurator.sharedInstance.configure(self)
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = DeleteOrderRequest()
    output.doSomething(request)
  }
  
  // MARK: Display logic
  
  func displaySomething(viewModel: DeleteOrderViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
