//
//  ShowItemsWorker.swift
//  CSRecruitmentTest
//
//  Created by msm72 on 08.08.16.
//  Copyright (c) 2016 Monastyrskiy Sergey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Alamofire
import Alamofire_Gloss
import CoreData


class ShowItemsWorker {
    // MARK: - Business Logic
    func loadData(request: ShowItemsRequest, completionHandler: (items: [Item]) -> Void) {
        // Get data from Core Data
        CoreDataManager.instance.fetchOrders(request.searchText) { (items) in
            if items.count > 0 || request.searchText != nil {
                print(items)
                
                completionHandler(items: items)
            } else {
                Alamofire.request(.GET, "http://localhost:8080/api/items", parameters: nil).responseArray(Item.self) { (response) in
                    switch response.result {
                    case .Success:
                        // Core Data: manipulate
                        dispatch_async(dispatch_get_main_queue()) {
                            // Core Data: add entities
                            CoreDataManager.instance.saveContext()
                            
                            self.loadData(request, completionHandler: completionHandler)
                        }
                        
                    case .Failure(let error):
                        print("Error = \(error)")
                    }
                }
            }
        }
    }
}

