//
//  ShowItemsConfigurator.swift
//  CSRecruitmentTest
//
//  Created by msm72 on 08.08.16.
//  Copyright (c) 2016 Monastyrskiy Sergey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension ShowItemsViewController: ShowItemsPresenterOutput {
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        router.passDataToNextScene(segue)
    }
}

extension ShowItemsInteractor: ShowItemsViewControllerOutput {
    
}

extension ShowItemsPresenter: ShowItemsInteractorOutput {

}


class ShowItemsConfigurator {
    // MARK: - Properties
    class var sharedInstance: ShowItemsConfigurator {
        struct Static {
            static var instance: ShowItemsConfigurator?
            static var token: dispatch_once_t = 0
        }
    
        dispatch_once(&Static.token) {
            Static.instance = ShowItemsConfigurator()
        }
    
        return Static.instance!
    }
  
  
    // MARK: - Configuration
    func configure(viewController: ShowItemsViewController) {
        let router = ShowItemsRouter()
        router.viewController = viewController
    
        let presenter = ShowItemsPresenter()
        presenter.output = viewController
    
        let interactor = ShowItemsInteractor()
        interactor.output = presenter
    
        viewController.output = interactor
        viewController.router = router
    }
}

