//
//  ShowItemsInteractor.swift
//  CSRecruitmentTest
//
//  Created by msm72 on 08.08.16.
//  Copyright (c) 2016 Monastyrskiy Sergey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol ShowItemsInteractorInput {
    func getItemsWith(request: ShowItemsRequest)
}

protocol ShowItemsInteractorOutput {
    func presentItemsForDisplayFrom(response: ShowItemsResponse)
}

class ShowItemsInteractor: ShowItemsInteractorInput {
    // MARK: - Properties
    var output: ShowItemsInteractorOutput!
    var worker = ShowItemsWorker()
  
    
    // MARK: - Business logic
    func getItemsWith(request: ShowItemsRequest) {
        // NOTE: Create some Worker to do the work
        self.worker.loadData(request, completionHandler: { (items) in
            let response = ShowItemsResponse(items: items)
            
            self.output.presentItemsForDisplayFrom(response)
        })
    }
}

