//
//  ShowItemsPresenter.swift
//  CSRecruitmentTest
//
//  Created by msm72 on 08.08.16.
//  Copyright (c) 2016 Monastyrskiy Sergey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol ShowItemsPresenterInput {
    func presentItemsForDisplayFrom(response: ShowItemsResponse)
}

protocol ShowItemsPresenterOutput: class {
    func displayItems(viewModel: ShowItemsViewModel)
}


class ShowItemsPresenter: ShowItemsPresenterInput {
    // MARK: - Properties
    weak var output: ShowItemsPresenterOutput!
  

    // MARK: - Presentation logic
    func presentItemsForDisplayFrom(response: ShowItemsResponse) {
        var itemsForDisplay: [ShowItemsViewModel.DisplayedItem] = []
        
        for item in response.items {
            let id = String(item.id)
            
            let itemForDispay = ShowItemsViewModel.DisplayedItem(name: item.name, comment: item.comment!, imageURL: item.imageURL!, id: id)
            
            itemsForDisplay.append(itemForDispay)
        }
        
        let viewModel = ShowItemsViewModel(displayedItems: itemsForDisplay)
        output.displayItems(viewModel)
    }
}

