# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iOSRecruitmentTest' do

	pod 'Nuke', '~> 3.1'
	pod 'Alamofire', '~> 3.4'
	pod 'Alamofire-Gloss', '~> 1.0'

end

